# Project: 06
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = "6\ 행렬.o"
LINKOBJ  = "6 행렬.o"
LIBS     = -L"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/lib" -L"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 06.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

"6\ 행렬.o": 6\ 행렬.c
	$(CC) -c "6 행렬.c" -o "6 행렬.o" $(CFLAGS)
